### ISSUE TITLE
Accessing PropTypes via the main React package

### ISSUE THREAD

**Issue by Xanatos38** [uraway/react-social-sharebuttons#18]
Hi,
I am using your package to display the Youtube button.

React (15.5.4) is displaying this error in dev mode:

> Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

Can you fix it please?

Here are some answers : https://stackoverflow.com/questions/43303761/accessing-proptypes-via-the-main-react-package-is-deprecated

**Comment by uraway** [comment]
Fixed version 2.1.3 released. Thank you for your report 👍
